FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# System deps
RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Python deps
COPY pyproject.toml poetry.lock* LICENSE /app/

RUN pip install --upgrade pip \
#  && pip install poetry \
#  && poetry config virtualenvs.create false \
#  && poetry install --no-interaction --no-ansi \
 && pip install .[tasks]


# App code
COPY api /app/api
COPY db /app/db
COPY server /app/server
COPY storage /app/storage
COPY utils /app/utils
COPY configs /app/configs
COPY docker/entrypoint.sh /app/docker/entrypoint.sh
COPY alembic.ini /app/alembic.ini
COPY alembic /app/alembic
COPY scripts /app/scripts
COPY results /app/results
COPY tasks /app/tasks
COPY utils /app/utils
COPY templates /app/templates
COPY prism /app/prism
COPY pipeline /app/pipeline
COPY data /app/data

RUN chmod +x /app/docker/entrypoint.sh


# Entrypoint
ENTRYPOINT ["sh", "/app/docker/entrypoint.sh"]
